### ISSUE TITLE
add the closing of unclosed tags

### ISSUE THREAD

**Issue by vivazzi** [divio/djangocms-snippet#12]
Hi, devs! You can improve your plugin, adding the checking unclosed tags. For example like that:
```
def tokenizer_html5lib(string):
    p = html5lib.HTMLParser(tree=treebuilders.getTreeBuilder("dom"))
    dom_tree = p.parseFragment(string)
    walker = treewalkers.getTreeWalker("dom")
    stream = walker(dom_tree)

    s = serializer.htmlserializer.HTMLSerializer(omit_optional_tags=False)
    return u''.join(s.serialize(stream))

content = tokenizer_html5lib('<div> test <p> p_test <span> some_test </p> quz </span> </div')
```

And add this check to model. For example:
```
# models.py 
class Snippet(models.Model):
    ...
    def get_html(self):
        return mark_safe(tokenizer_html5lib(self.html))

# snippet.html
{{ instance.get_html }}
```

I think you find this code useful for this plugin :)

**Comment by mkoistinen** [comment]
Nice, thank you. Care to make a PR?

**Comment by FinalAngel** [comment]
I'm not a fan of adding html sanitising here as it might complicate things and this is not really a rich-text-editor feature. However we will add "Ace" as of #10. Ace will show errors in your code so it acts like an IDE.
