### ISSUE TITLE
Fix migrations bit on doc

### ISSUE THREAD

**Issue by Lacrymology** [divio/djangocms-snippet#19]
The docs say 

* If using Django 1.6 and South < 1.0.2 add 'djangocms_snippet': 'djangocms_snippet.migrations_django', to SOUTH_MIGRATION_MODULES (or define SOUTH_MIGRATION_MODULES if it does not exist).

when it's actually `djangocms_snippet.south_migrations`

**Comment by FinalAngel** [comment]
obsolete in https://github.com/divio/djangocms-snippet/pull/28
