### ISSUE TITLE
Bad Request 400 on add with CMS 3.0.6 and Django 1.7

### ISSUE THREAD

**Issue by Noah-A** [divio/djangocms-snippet#2]
When I try to add a new snipped in frontend editing the modal window opens and when I press the green plus sign to add a new snippet the popup opens and returns a "Bad Request 400" error.

Removing the _to_field=id segment of the querystring from the admin URL fixes the issue and allows adding a new snippet.

**Comment by mkoistinen** [comment]
I'm unable to reproduce this in recent CMSs. Closing for now, but if this occurs again and is repeatable (Ie, not a project-specific issue), please re-open.
