### ISSUE TITLE
Snippets can't actually be edited in the edit model.

### ISSUE THREAD

**Issue by Noah-A** [divio/djangocms-snippet#3]
CMS 3.0.6 Django 1.7

When in frontend structure editing if I have a snippet and choose "edit" the modal window which opens only allows selecting different existing snippets or adding new ones. I can't actually edit the content of an existing one.

**Comment by carn1x** [comment]
I'm also experiencing this. Is this even a bug or a feature request?

**Comment by yakky** [comment]
This is how this plugin has ever worked. I think it would be a nice improvement to allow editing the snipped from the plugin.

**Comment by mkoistinen** [comment]
As @yakky states, this is the current design. PRs welcome! =)

**Comment by FinalAngel** [comment]
This is now possible :)
