### ISSUE TITLE
As a dynamic plugin, needs to have cache=False

### ISSUE THREAD

**Issue by fp4code** [divio/djangocms-snippet#37]
When not in edit mode, menus called from snippets were frozen.

In fact djangocms-snippet is a dynamic plugin. Hence it needs to have cache=False
Cf. http://docs.django-cms.org/en/release-3.4.x/upgrade/3.0.html#placeholder-caching

**Comment by llherbier** [comment]
I do not agree here, in many cases snippets are static code (html/js/css) and thus must be cached. It could be an option, but should not be the default behaviour.

**Comment by fp4code** [comment]
Snippets are very useful when templatetags {% ... %} are included. The default behavior should be correctness, not efficiency.

**Comment by llherbier** [comment]
in the documentation, Django-snippet main use case is to add "HTML, CSS or JavaScript snippets into your website". Using template tags inside a snippet does not seems to be part of the supported use case but more a side effect of how snippets have been implemented. It can be a nice feature but it should not impact the default behaviour.

**Comment by fp4code** [comment]
Further in the documentation, it's written "This plugin should only be used during the initial development phase for rapid prototyping and testing". Efficiency is not a major concern during initial development phase!

**Comment by fp4code** [comment]
Solved with Pull Request #47.

**Comment by FinalAngel** [comment]
@fp4code as mentioned in the PR, the solution would be to add the cache option added to the plugin itself when authoring. Let's see if we can implement this in the next couple of months :)
