### ISSUE TITLE
Missing Django 1.7 migrations when installing from PyPI

### ISSUE THREAD

**Issue by cimocimocimo** [divio/djangocms-snippet#5]
When I installed this package from PyPI I got an invalid bases error when running the initial migrations.
```sh
pip install djangocms-snippet
```

I thought that was odd since I thought I had previously installed the package using pip before and I did get the migrations_django directory. I first noticed the problem when deploying to AWS Elastic Beanstalk. I started getting the invalid bases error there. I troubleshot the problem to the missing migrations_django directory in site-packages. After uninstalling the package and manually deleting the package from the site-packages locally and then reinstalling the package did I see that the directory was missing.

To get it working I simply installed directly from github
```sh
pip install git+git://github.com/divio/djangocms-snippet.git
```

To get pip freeze > requirements.txt to show the git repo url I used this command
```sh
pip install -i git+git://github.com/divio/djangocms-snippet.git#djangocms_snippet
```

**Comment by yakky** [comment]
Updated version uploaded to PiPy
