### ISSUE TITLE
should snippet content be searchable?

### ISSUE THREAD

**Issue by czpython** [divio/djangocms-snippet#6]
django-cms comes with a built in search feature, should snippet content be allowed to be searchable? Considering there can be all sorts of content in a snippet like django tags, javascript, etc..

I think we should make it a setting that defaults to False to keep backwards compatibility

**Comment by mkoistinen** [comment]
+1

**Comment by vstoykov** [comment]
Because #7 is merged probably this need to be closed

**Comment by czpython** [comment]
Fixed by #7
