### ISSUE TITLE
Uncaught TypeError: this.ui.container.data(...).push is not a function

### ISSUE THREAD

**Issue by pinksharpii** [divio/djangocms-snippet#64]
I am setting up a new Django CMS site and am running into this issue when I try to edit a page. It happens when I click the little icon in the top right of the toolbar to switch to structure view. It is only happening on Django CMS pages. Any Aldryn Newsblog list views or single views are fine, as are a custom model I made for Events. I can go into structure view on those without issue. 

I don't know Django well enough to debug much further from here. I have tried removing some custom plugins from the project and blocks from the template with no luck. 

We are on Django 2.2 and CMS 3.7.0

**Comment by FinalAngel** [comment]
@pinksharpii is this affecting djangocms-snippet? Cause that seems more a newsblog, events or django cms issue. Please let me know :)

**Comment by pinksharpii** [comment]
How do I know if it's affecting djangocms snippet?
How is it a newsblog issue if that's the one thing that does work properly? It's the cms pages that are the problem.

**Comment by FinalAngel** [comment]
@pinksharpii this is the djangocms-snippet repository, it would be nice if you could create an issue then on the django-cms project :)

Also if its related to the media files, make sure the old django CMS files are not cached, as they change from say 3.6 to 3.7: https://github.com/divio/django-cms/tree/release/3.7.x/cms/static/cms/js/dist/3.7.0

**Comment by pinksharpii** [comment]
oh my bad. I thought it was for the CMS.

**Comment by FinalAngel** [comment]
no worries @pinksharpii , thank you very much :)
